### ISSUE TITLE
Remotefork PHP не поддерживает DLNA

### ISSUE THREAD

**Issue by baragoon** [bobi/ForkPlayer#1]
по урлу /treeview получаю
```
<?xml version="1.0" encoding="UTF-8"?>
<items><channel><title><![CDATA[RemoteFork PHP]]></title><description><![CDATA[RemoteFork PHP не поддерживает DLNA]]></description></channel></items>
```
Хотя по урлу /localvideo вываливает список файлов.
ЧЯДНТ?

**Comment by bobi** [comment]
на стартовой странице нажмите "Перейти по адресу", введите URL http://IP:89 и добавьте его на стартовую страницу

**Comment by bobi** [comment]
добавил поддержку RmoteFork DLNA иконки, обновите .htaccess файл.

**Comment by baragoon** [comment]
Спасибо, получилось, правда не все файлы проигрывает, пока еще не понял зависимость.

**Comment by bobi** [comment]
возможно проблемы с пробелами или русскими именами файлов
