### ISSUE TITLE
error ForkPlayer

### ISSUE THREAD

**Issue by powercode-team** [bobi/ForkPlayer#11]
После сегодняшнего обновления форкплеера , начал писать ошибку что установите версию выше 1.2, 
пробовал изменения с репозитория последние брать , но не помогло , error log чистый, телевизор LG

**Comment by bobi** [comment]
что обновилось?
как воспроизвести ошибку?

**Comment by rezonans65** [comment]
46.36.222.114 - днс на который вчера переключился , стартовый зеленый сплэш скрин при запуске, и вот с ним теперь отказывается работать

**Comment by bobi** [comment]
не могу воспроизвести, интерйфейс новый, телевизор LG. попробуйте воспроизвести тут http://operatv.obovse.ru/2.5/?dev=in

**Comment by powercode-team** [comment]
вчера само все нормализовалось , проблема была точно не отсюда - потому что ничего больше менял
