### ISSUE TITLE
Настройка php.

### ISSUE THREAD

**Issue by RomanGoncharov** [bobi/ForkPlayer#12]
Здравствуйте. Не могли бы вы, пожалуйста,  добавить в Readme настройку php и всё что с ним связано?

**Comment by bobi** [comment]
Это невозможно, так как для каждого устройства способ установки и настройки разные. Для примера на nas wdmycloud нужно только настроить апач, а на роутере нужно установить php, при этом скорее всего нужно сначала сменить прошивку чтобы была возможность установки php. Для каждого устройства нужно читать форумы по этому устройству.

**Comment by RomanGoncharov** [comment]
У меня есть сервер на debian, можете написать инструкцию по установке, пожалуйста?

**Comment by bobi** [comment]
Я не эксперт в установке, вам нужно установить: php, Apache или nginx, конфиги есть в readme. А инструкций по установке полно в интернете гугл в помощь.
https://www.google.com.ua/search?q=debian+install+php+apache&oq=debian+install+php+apache&aqs=chrome..69i57.12972j0j7&sourceid=chrome-mobile&ie=UTF-8
