### ISSUE TITLE
Не все файлы проигрывает

### ISSUE THREAD

**Issue by LinkSayrus** [bobi/ForkPlayer#14]
Не все файлы проигрывает плеер. Не могу понять почему такое происходит. 
Файл виден, он запускается, но после некоторого времени выдает попытка соединения 2 ... 3 и т.д. 
В логах апача запросы отображаются примерно одинаково как к работающему файлу так и к не работающему. 

Работающий:
"GET /localvideo/Downloads/Beyond.Skyline.2017.BDRip.1080p%20%5BNG%5D%20iTunes.mkv HTTP/1.1" 206 4676523548 "-" "Lavf52.34.0"

Не работающий:
"GET /localvideo/Downloads/Geostorm.2017.BDRip.%281080p%29.mkv HTTP/1.1" 206 8528182572 "-" "Lavf52.34.0"

Не подскажите куда копать и что можно сделать?

**Comment by bobi** [comment]
возможно проблема с кодеком самого телевизора. еще попробуйте переименовать файл без пробелов и спец символов и попробуйте дать короткое имя файлу.

**Comment by LinkSayrus** [comment]
Так в этом то и проблема что файл проигрывается если на флешку закинуть а удаленно не хочет. 
Пробовал файлу дать имя 1.mkv тоже ниче не получилось. 

вот такое выдает:
GET /localvideo/1.mkv HTTP/1.1" 206 8528182572 "-" "Lavf52.34.0"
"GET /localvideo/1.mkv HTTP/1.1" 206 157382 "-" "Lavf52.34.0"
GET /localvideo/1.mkv HTTP/1.1" 206 124612 "-" "Lavf52.34.0"
GET /localvideo/1.mkv HTTP/1.1" 206 26305 "-" "Lavf52.34.0"
GET /localvideo/1.mkv HTTP/1.1" 206 25654 "-" "Lavf52.34.0"
GET /localvideo/1.mkv HTTP/1.1" 416 314 "-" "Lavf52.34.0"
GET /localvideo/1.mkv HTTP/1.1" 206 8528182572 "-" "Lavf52.34.0"
GET /localvideo/1.mkv HTTP/1.1" 206 157382 "-" "Lavf52.34.0"

**Comment by bobi** [comment]
в случае c php remotefork, телевизор получает прямую ссылку и сам remotefork не задействован при проигрывании.
можно попробовать воспроизвести проблему в браузере и через Dev Tools посмотреть на запросы и ответы от апача, может удастся идентифицировать проблему http://operatv.obovse.ru/2.5/?dev=in#0.9061221988306218

**Comment by LinkSayrus** [comment]
У загрузок файлов отличается показатель Range как будто у не работающего файла проигрыватель пытается загрузить весь файл целиком и у него не получается, а у работающего файла по кускам грузит.

Не знаю может это поможет чем-то вот лог дебага:

Работающий:
```
[authz_core:debug] [pid 9377] mod_authz_core.c(806): [client 10.250.0.16:48405] AH01626: authorization result of <RequireAny>: granted
[http:debug] [pid 9377] byterange_filter.c(295): [client 10.250.0.16:48405] AH01583: Range: 0- | 0-11332099770 (0 : 0 : 11332099771)
[authz_core:debug] [pid 9386] mod_authz_core.c(806): [client 10.250.0.16:48406] AH01626: authorization result of Require all granted: granted
[authz_core:debug] [pid 9386] mod_authz_core.c(806): [client 10.250.0.16:48406] AH01626: authorization result of <RequireAny>: granted
[http:debug] [pid 9386] byterange_filter.c(295): [client 10.250.0.16:48406] AH01583: Range: 11332053343- | 11332053343-11332099770 (0 : 0 : 11332099771)
[authz_core:debug] [pid 9379] mod_authz_core.c(806): [client 10.250.0.16:48407] AH01626: authorization result of Require all granted: granted
[authz_core:debug] [pid 9379] mod_authz_core.c(806): [client 10.250.0.16:48407] AH01626: authorization result of <RequireAny>: granted
[http:debug] [pid 9379] byterange_filter.c(295): [client 10.250.0.16:48407] AH01583: Range: 6519- | 6519-11332099770 (0 : 0 : 11332099771)


```
Не работающий:
 ```
mod_authz_core.c(806): [client 10.250.0.16:43326] AH01626: authorization result of <RequireAny>: granted
[http:debug] [pid 9386] byterange_filter.c(295): [client 10.250.0.16:43326] AH01583: Range: 0- | 0-8528182571 (0 : 0 : 8528182572)
[authz_core:debug] [pid 9378] mod_authz_core.c(806): [client 10.250.0.16:43327] AH01626: authorization result of Require all granted: granted
 [authz_core:debug] [pid 9378] mod_authz_core.c(806): [client 10.250.0.16:43327] AH01626: authorization result of <RequireAny>: granted
 [http:debug] [pid 9378] byterange_filter.c(295): [client 10.250.0.16:43327] AH01583: Range: 8528025190- | 8528025190-8528182571 (0 : 0 : 8528182572)
authz_core:debug] [pid 9380] mod_authz_core.c(806): [client 10.250.0.16:43328] AH01626: authorization result of Require all granted: granted
 [authz_core:debug] [pid 9380] mod_authz_core.c(806): [client 10.250.0.16:43328] AH01626: authorization result of <RequireAny>: granted
[http:debug] [pid 9380] byterange_filter.c(295): [client 10.250.0.16:43328] AH01583: Range: 8528057960- | 8528057960-8528182571 (0 : 0 : 8528182572)

```

Причем если работающий файл начал проигрывание то запросы перестают сыпаться. Все останавливается на первом куске:
`Range: 6519- | 6519-11332099770 (0 : 0 : 11332099771)
`
А у не работающего запросы постоянно повторяются:

`Range: 8528057960- | 8528057960-8528182571 (0 : 0 : 8528182572)`

Может это поможет чем-то.

**Comment by bobi** [comment]
врятли, remotefork php тут не принимает участия. после того как он отдал ссылку на файл плееру (в вашем случае) работает плеер и апач на прямую без участия remotefork.
попробуйте открыть тот же файл в обычном браузере через http://operatv.obovse.ru/2.5/?dev=in#0.9061221988306218, или попробуйте запустить на телевизоре но с другим плеером.
