### ISSUE TITLE
tree.tv не работает

### ISSUE THREAD

**Issue by ghost** [bobi/ForkPlayer#16]
Перестал работать tree.tv. 
При выборе любого файла пишет needremotefork. 
С remotefork для других платформ все работает.

**Comment by bobi** [comment]
изменений в этом коде у оригинального remotefork небыло более года и у меня tree.tv работает нормально.

**Comment by ghost** [comment]
Хм, странно. Работало, но сейчас перестало. С ремотфорком на андройде работает.

**Comment by blackcatss** [comment]
В продолжении темы. Телевизор LG (LM серия)  виснет на старте воспроизведения контента tree.tv. RemoteFork на Entware+nginx, тест проходит. С remotefork для Android все работает.

**Comment by bobi** [comment]
Какое видео не работает на RemoteFork?

**Comment by blackcatss** [comment]
Все видео из Tree.tv. Ссылка обрабатывается, запускается плеер (в настройках HTML5), в плеере указывается длительность файла, после вылет из ForkPlayer на темный экран, реакция на нажатие клавиш на пульте - инфо полоса вверху (как при просмотре эфирки), помогает только полное перевключение телевизора. Пробовал также в связке Entware+debian в chroot (Apace2 php7) результат тот же.

**Comment by bobi** [comment]
понятия не имею что может быть не так, у меня tree.tv работает. все что делает RemoteFork это дает правильную ссылку плееру. попробуйте посмотреть и сравнить ссылки на компьютере через http://operatv.obovse.ru/2.5/?dev=in#0.9540964870456017

**Comment by RuslanOnyshchenko** [comment]
Не работает потому что со стороны форкплеера в файле forkplayer.js в функции tw5 ожидается наличие \n\n перед #EXTM3U в ответе. В php версии \n\n нет. Как вариант фикса можно в remotefork в файле parserlink.php перед return $result; добавить что-то типа 
$result = str_replace('#EXTM3U', PHP_EOL.PHP_EOL.'#EXTM3U', $result);
У себя локально уже сделал, Tree.TV заработал

**Comment by RuslanOnyshchenko** [comment]
Но по хорошему, нужно чтобы разработчик forkplayer сделал изменение в файле forkplayer.js в строке #27547, в функции «tw5» заменить код:

function tw5(u,sel,mini, pl,yk,title,parse_url,remote,s){
	if(s.indexOf("Connection:")>0&&s.indexOf("Server:")>=0){
		setcook(s);
		var x=s.indexOf("\n\n")+2;
		if(x==1) x=s.indexOf("\r\n\r\n")+4;
		if(x>4) s=s.substr(x);
	}setcook(s);
	//kjtYpr.lQO000OIS0UHII1l0O1Ypr(0);
	if(s.indexOf("#EXTM3U")==-1){
		if(remote) return;
		apptree=false;
		kjtYpr.lQO000OIS0UHII1l0O1Ypr(0,0); 
		ll0OOO_gh1Il1OYpr(true);
		kjtYpr.popUp("Tree.tv: error 4<br>need remotefork"+s,2000);
		fpp= "";
		return;
	}
	console.log("TREE SESSION RES4="+s);

На этот:

function tw5(u,sel,mini, pl,yk,title,parse_url,remote,s){
	if(s.indexOf("Connection:")>0&&s.indexOf("Server:")>=0){
		setcook(s);
		//var x=s.indexOf("\n\n")+2;
		//if(x==1) x=s.indexOf("\r\n\r\n")+4;
		//if(x>4) s=s.substr(x);
	}setcook(s);
	//kjtYpr.lQO000OIS0UHII1l0O1Ypr(0);
	if(s.indexOf("#EXTM3U")==-1){
		if(remote) return;
		apptree=false;
		kjtYpr.lQO000OIS0UHII1l0O1Ypr(0,0); 
		ll0OOO_gh1Il1OYpr(true);
		kjtYpr.popUp("Tree.tv: error 4<br>need remotefork"+s,2000);
		fpp= "";
		return;
	}
	s=s.substring(s.indexOf("#EXTM3U"));
	console.log("TREE SESSION RES4="+s);

**Comment by bobi** [comment]
спасибо, я нашел несоответствие кода php c оригинальным remotefork.
ваш фикс больше похож на хак поэтому пул риквест отменил и исправил в соответствии с кодом оригинального remotefork.

**Comment by blackcatss** [comment]
Потестил исправления, в моем случае все без изменений LG 12года виснет на Tree.tv. Сравнил ссылки получаемые от андроид (приложение работает) и РНР версий:
РНР: `/proxym3u8BaHR0cDovL3N0NC4zdHYuaW0vcGxheS8wOGJjMDU3MjMxZWFlYzg1NDU4ZDZlNTEzMDNhYmM0MC83MjBwX0hpZ2guV2lyZS5BY3QubXA0L2luZGV4Lm0zdThPUFQ6UmVmZXJlci0taHR0cDovL3BsYXllci50cmVlLnR2Ly0tT3JpZ2luLS1odHRwOi8vcGxheWVyLnRyZWUudHZPUEVORDo=endbase64/`
Андроид:
`/proxym3u8BaHR0cDovL3N0NC4zdHYuaW0vcGxheS80ZDMwMDI1YjI4ZDNhNjE5ZDgwMjQ2Mjk3ZjdmNjcyMi83MjBwX0hpZ2guV2lyZS5BY3QubXA0L2luZGV4Lm0zdThPUFQ6UmVmZXJlci0taHR0cDovL3BsYXllci50cmVlLnR2Ly0tT3JpZ2luLS1odHRwOi8vcGxheWVyLnRyZWUudHZPUEVORDo=endbase64/seg-4-v1-a1.ts`

**Comment by bobi** [comment]
с сылками вида proxym3u8 и treetv вообще загадка, они то работают то нет и на оригинальном remotefork.

**Comment by blackcatss** [comment]
Куда добавить в код и какие строки (пардон за мой плохой РНР), чтоб на выходе получить ссылку с концовкой ...=endbase64/index.m3u

**Comment by bobi** [comment]
в код ничего добавлять ненужно - ссылки формирует forkplayer, не remotefork
