### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by baragoon** [bobi/ForkPlayer#2]
Под nginx не пробовали запускать? Пока что колупаюсь, но безрезультатно)

**Comment by bobi** [comment]
нет, я с nginx никогда не работал

по идее должно быть что-то типа:
обратите внимание что путь к папке с видео указан в двух разных местах.
если заведете выложите конфиг.
и скачайте последний код
```nginx
server {
	listen 89;
	charset utf-8;

	root /Path/to/forkplayer/script/www/;
	index index.php;
	server_name localhost;

	location / {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/$ /index.php break;
	}
	location /localvideo {
		alias /Path/to/Folder/with/videos/;
		autoindex on;
	}
	location /test {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/test/?$ /test.php break;
	}
	location /parserlink {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/parserlink/?$ /parserlink.php break;
	}
	location /treeview {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/treeview/?$ /index.php break;
	}
	location /plugin/NetworkResources {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/plugin/([^/]+)/?$ /index.php?plugin=$1&FP_LOCAL_VIDEO_PATH=/Path/to/Folder/with/videos/ break;
	}
	location /plugin {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/plugin/([^/]+)/?$ /index.php?plugin=$1 break;
	}
}
```

**Comment by baragoon** [comment]
Листинг директории получаю, из форкплеера "видно" что ремоут запущен, но при открытии папки с видео получаю ошибку парсинга листа или 404

`server {
    listen 89;
    charset utf-8;

    root /usr/share/nginx/html/remotefork;
    index index.php;
    server_name localhost;

    location /localvideo {
        alias /media/torrents/Downloads;
        autoindex on;
    }

    # nginx configuration
    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Content-type "text/html; charset=UTF-8";
        rewrite ^/$ /index.php break;
    }
    location /test {
        add_header Access-Control-Allow-Origin *;
        add_header Content-type "text/html; charset=UTF-8";
        rewrite ^/test/?$ /test.php break;
    }
    location /parserlink {
        add_header Access-Control-Allow-Origin *;
        add_header Content-type "text/html; charset=UTF-8";
        rewrite ^/parserlink/?$ /parserlink.php break;
    }
    location /treeview {
        add_header Access-Control-Allow-Origin *;
        add_header Content-type "text/html; charset=UTF-8";
        rewrite ^/treeview/?$ /index.php break;
    }
    location /plugin/NetworkResources {
        add_header Access-Control-Allow-Origin *;
        add_header Content-type "text/html; charset=UTF-8";
        rewrite ^/plugin/([^/]+)/?$ /index.php?plugin=$1&FP_LOCAL_VIDEO_PATH=/media/torrents/Downloads break;
    }
    location /plugin {
        add_header Access-Control-Allow-Origin *;
        add_header Content-type "text/html; charset=UTF-8";
        rewrite ^/plugin/([^/]+)/?$ /index.php?plugin=$1 break;
    }
    location ~ .php$ {
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_pass        backend;
        fastcgi_index       index.php;
        fastcgi_param       SCRIPT_FILENAME /usr/share/nginx/html/remotefork$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param       QUERY_STRING    $query_string;
        fastcgi_param       REQUEST_METHOD  $request_method;
        fastcgi_param       CONTENT_TYPE    $content_type;
        fastcgi_param       CONTENT_LENGTH  $content_length;
        fastcgi_intercept_errors    on;
        fastcgi_ignore_client_abort off;
        fastcgi_connect_timeout             600s;
        fastcgi_send_timeout                600s;
        fastcgi_read_timeout                600s;
        fastcgi_buffer_size         128k;
        fastcgi_buffers                     4       256k;
        fastcgi_busy_buffers_size   256k;
        fastcgi_temp_file_write_size        256k;
        fastcgi_param       FP_LOCAL_VIDEO_PATH     /media/torrents/Downloads;
    }
}
`

**Comment by bobi** [comment]
а какой ответ по урлу http://IP:89/plugin/NetworkResources ?

**Comment by baragoon** [comment]
dispatch(); libxml_clear_errors();

**Comment by bobi** [comment]
уберите 

этот маппинг

location /plugin/NetworkResources {
		add_header Access-Control-Allow-Origin *;
		add_header Content-type "text/html; charset=UTF-8"
		rewrite ^/plugin/([^/]+)/?$ /index.php?plugin=$1&FP_LOCAL_VIDEO_PATH=/Path/to/Folder/with/videos/ break;
	}

**Comment by bobi** [comment]
и какой ответ по урлу http://ip:89?

**Comment by bobi** [comment]
так как похоже что у вас PHP не отрабатывает а просто показывает исходный код

**Comment by baragoon** [comment]
вот если убрать маппинг, то http://IP:89/plugin/NetworkResources  открывает index.php плейнтекстом
http://ip:89 тоже, если задать http://ip:89/index.php, то вижу xml-лину, видимо с php-fmp не до конца подружилось

**Comment by bobi** [comment]
похоже что-то не так с rewrite

**Comment by baragoon** [comment]
100%

**Comment by baragoon** [comment]
В общем, забил пока что на nginx... На работе есть коллеги, которые в вопросе разбираются, как нибудь попробуем разобраться с реврайтвми. 
З. Ы. А если в имени файла есть пробел, то форк его не играет - 404. Надо почитать по этому поводу. Прошу issue не закрывать, может кто по поводу nginx что-то еще подскажет.

**Comment by bobi** [comment]
У меня играет с пробелами без проблем, это скорее всего проблема с настройкой апача, так как форк просто получает ссылку на апач, можно посмотреть какая ссылка приходит в xml от форка и попробовать открыть ее в браузере

**Comment by baragoon** [comment]
браузер нормально "ловит" урлы с пробелами, а вот в форке не ловит. Если бы было что-то не так в этом плане с апачем, то и браузер бы не обрабатывал пробелы в урле или я не прав?

**Comment by baragoon** [comment]
Проверил и на телике и на телефоне с андроидом (через приложение) и на айфоне через браузер.
Не важно, русские названия или английские - если есть пробел или в названии файла или в названии папки (проверял на ext4 и на xfs) - файл не играется. Конфиг апача тупо стандартный.

**Comment by baragoon** [comment]
Я не силен в php, но методом научного тыка, полагаю, что нужно в файле ForkPlayer/Utils/Serializer.php где-то в этой части
`                    case ItemType::FILE:
                        $elem = $xml->createElement("stream_url");
                        $elem->appendChild($xml->createCDATASection($channel->getLink()));
                        $chElement->appendChild($elem);
                        break;
`
нужно, что бы пробелы в урле заменялись на %20

**Comment by bobi** [comment]
да, скорее всего у вас апач не понимает ссылки с пробелами, а у меня понимает. по правильному нужно ссылку энкодить, я это сделю, но пока просто вемени нету, сегодня, завтра думаю сделаю.

**Comment by baragoon** [comment]
Апач то понимает, браузером эти файлы качаются...
по сути, то ли курлу нужно скармливать урл в "кавычках", то ли заменять пробел на %20
Буду с нетерпением ждать фикс.
Чисто ради интереса, у Вас какая версия апача и на чем крутится?

**Comment by bobi** [comment]
Apache/2.4.10 на WDMycloud там какя-то версия Debian стоит, но в любом случае эту проблему я собирался чинить так-как под Windows не работает тоже.

**Comment by bobi** [comment]
попробуйте последний код добавил энкодинг урлов

**Comment by baragoon** [comment]
Огонь) По крайней мере с пробелами и с русскими названиями играет. Если что-то найду не то - сообщу.
БОЛЬШОЕ спасибо!

**Comment by bobi** [comment]
добавил пример конфига nginx в README, проверял под Windows

**Comment by baragoon** [comment]
закинул обновленный конфиг в nginx, через впн проверил телефоном с андроидом - все работает.
Еще раз ОГРОМНОЕ спасибо!
