### ISSUE TITLE
Exclude files\dirs

### ISSUE THREAD

**Issue by baragoon** [bobi/ForkPlayer#22]
Please advise how to exclude some files and\or directories from listing?
For example, Synology DSM generates "@eaDir" directory which I don't want to see in list.
Thank you.

**Comment by bobi** [comment]
there is no way to exclude dirs, you can modify following plugin to exclude some dirs https://github.com/bobi/ForkPlayer/blob/6b2b14caf506992d8f97043f8a2c2ed418d4d98b/ForkPlayer/Plugins/Local/plugin.php#L68
