### ISSUE TITLE
Serializer.php

### ISSUE THREAD

**Issue by elanski** [bobi/ForkPlayer#4]
Fatal error: Call to undefined function ForkPlayer\Utils\json_encode() in /opt/share/nginx/html/ForkPlayer/Utils/Serializer.php on line 165

**Comment by bobi** [comment]
what version of php do you use?

**Comment by elanski** [comment]
Php  5.6.29

установил json, теперь другая ошибка 

{"playlist_name":"All Plugins","channels":[{"title":"Network Resources","description":"Network Resources","playlist_url":"http:\/\/192.168.2.1:89\/plugin\/NetworkResources","logo_30x30":"http:\/\/192.168.2.1:89\/img\/local-network.png"}]}



Отправлено со смартфона Sony Xperia™

----Пользователь Andrey B. написал ----

**Comment by bobi** [comment]
так, а в чем ошибка? это правильный ответ сервера.

**Comment by elanski** [comment]
телевизор не получает ссылок. Запускаю клиент на ПК, все ОК.

**Comment by bobi** [comment]
проверьте настройки телевизора, Remote Fork должен быть настроен вручную и нужно указать там  192.168.2.1:89.
так же можете провереть таким способом - в стартовом меню ForkPlayer выбрать перейти по адресу и ввести http://192.168.2.1:89

**Comment by elanski** [comment]
Настройки в форке есть 192.168.2.1:89
перейти по адресу и ввести http://192.168.2.1:89 fork link - ошибка парсинга плейлиста

**Comment by bobi** [comment]
а раньше сервер работал?

**Comment by elanski** [comment]
На ПК и на андроиде все ОК.
Попробовал поставить на роутер, не получается.

**Comment by bobi** [comment]
обновил код, попробуйте с новым кодом.

**Comment by elanski** [comment]
Опять ошибка парсинга плейлиста

**Comment by bobi** [comment]
даже незнаю что вам еще посоветовать, у меня на двух телевизорах LG все работает без проблем.

**Comment by elanski** [comment]
мож пакета какого-то не хватает? entware.
DLNA работает нормально, только с кирилицей не дружит.

**Comment by bobi** [comment]
я на роутере не пробоал запускать, у меня работает на NAS.

**Comment by elanski** [comment]
apache или nginx  у вас на NAS?

**Comment by bobi** [comment]
apache, но конфиг для nginx тоже есть в readme, nginx проверял только под windows

**Comment by elanski** [comment]
На nginx ставил, DLNA работает, ремотефорк запускается и дает листинг файлов, а ссылок нет. Запускаю ремотефорк на ПК, анроиде все ок.

**Comment by bobi** [comment]
какой конфиг nginx?
какой ответ от сервера?

**Comment by elanski** [comment]
worker_processes  1;

events {
    worker_connections  64;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

     sendfile        on;

    keepalive_timeout  65;

    #gzip  on;

    server {
    listen 89;
    charset utf-8;

    root /opt/share/nginx/html;
    index index.php;
    server_name localhost;

    default_type application/json;
    add_header Access-Control-Allow-Origin *;

    location /localvideo {
        alias /opt;
        autoindex on;
    }
    location / {
        rewrite ^/$ /index.php;
    }
    location /test {
        rewrite ^/test/?$ /test.php;
    }
    location /parserlink {
        rewrite ^/parserlink/?$ /parserlink.php;
    }
    location /treeview {
        rewrite ^/treeview/?$ /index.php;
    }
    location /plugin {
        rewrite ^/plugin/([^/]+)/?$ /index.php?plugin=$1;
    }
    location ~ .php$ {
        fastcgi_pass   127.0.0.1:9123;
        fastcgi_index  index.php;
        fastcgi_param FP_LOCAL_VIDEO_PATH /opt;
		fastcgi_param OUTPUT_FORMAT json;
        include fastcgi.conf;
        include fastcgi_params;         
    }
}
}
На примере Nowfilms видно только трейлер, и не открывает его.
Когда ремотефорк на ПК видно список фильма разного качества и все открывает.

**Comment by bobi** [comment]
уберите для начала 
fastcgi_param OUTPUT_FORMAT json;

есть ли в папке /opt файлы?

что выдает сервер по адресу http://192.168.2.1:89?

**Comment by elanski** [comment]
В папке файлы есть он их видит и успешно показывает.
что выдает сервер по адресу http://192.168.2.1:89?
Через браузер
{"playlist_name":"All Plugins","channels":[{"title":"Network Resources","description":"Network Resources","playlist_url":"http:\/\/192.168.2.1:89\/plugin\/NetworkResources","logo_30x30":"http:\/\/192.168.2.1:89\/img\/local-network.png"}]}
Через форк   link ошибка парсинга плейлиста

**Comment by bobi** [comment]
уберите fastcgi_param OUTPUT_FORMAT json; чтобы вывод был в xml может проблема с json

**Comment by bobi** [comment]
и уберите default_type application/json;

**Comment by elanski** [comment]
Строчки не убирал, посмотрел лог ошибок пхп, там был парсерлинк, увидел, что нужны пакеты пхп -curl -mbstring. Поставил - заработало Nowfilm, ссылки появились.

**Comment by bobi** [comment]
Отлично

**Comment by elanski** [comment]
А как быть с tree.tv? И еще у меня есть подписка на nstreamportal.ru ссылки есть, но не открывает. Tushkan и bobfilm меня интересуют. Спасибо большое за ваш труд и помощь.

**Comment by bobi** [comment]
Я не разработчик fork плеера, так что не знаю почему может не работать, я лишь переписал часть remote fork на php, которая отвечала за отображение локальных файлов и часть которая парсила ссылки

**Comment by bobi** [comment]
обновите код tree.tv должен заработать, добвил поддержку treeview

**Comment by bobi** [comment]
нужно так же обновить конфиг nginx
