### ISSUE TITLE
acestream

### ISSUE THREAD

**Issue by baragoon** [bobi/ForkPlayer#6]
Было бы очень шикарно, реализовать поддержку в remotefork_php acestream engine на linux-подобных системах.

**Comment by bobi** [comment]
сейчас нету времени этим заниматся и скорее всего нужно делать поддержку в самом форкплеере

**Comment by baragoon** [comment]
На все что хочется, времени всегда не хватает)
С виндовым ремоут-форком торренты работают, с ромоутом на андроид тоже.
Так что поддержка в самом плеере есть, нету именно в Вашем форке.
